<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <RootNamespace>MiniOcr</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFtoImage" Version="5.4.0" />
    <PackageReference Include="Sdcb.SimdPaddleOCR" Version="1.4.1" />
    <PackageReference Include="Sdcb.SimdPaddleOCR.Models.ChineseV6Tiny" Version="1.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="samples/sample-multipage.pdf" LogicalName="MiniOcr.samples.sample-multipage.pdf" />
    <None Include="samples/sample-multipage.pdf" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
